[package]
name = "overcast"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-gossip = "2.2.0"
solana-sdk = "2.2.1"
solana-streamer = "2.2.0"
solana-core = "2.2.2"
signal-hook = "0.3"
solana-net-utils = "2.2.2"
libc = "0.2.171"
heapless = "0.8.0"
